# -*- coding: utf-8 -*-
"""Aul6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AB2YLBD9k9rDWlj3QyRlaD7lBd0JgGcS
"""

# nome = "Diogo"
# indices comecçam com 0
#.append adiciona
# lista.append(10)v


# lista = [1,2,3,4,"casa", True]
# print(lista)

# lista2 = [1,2,33,23,556,]
# # lista2.remove(33) *pelo valor que esta na lista
# # print(lista2)

# del lista2[4] *pelo indice da lista
# print(lista2)

# lista3 = [1,2,3,65,3,55,998,33,45]
# comprimento = len(lista3)
# print(comprimento)

# lista5 = [1,2,3,6,5,44,55,77,99,74]
# for i in lista5:
#     print(i)


#................                 .......................................           ........................               ..........................           .................. .


# **Exercício 1:** Crie uma lista chamada `numeros` que contenha os números inteiros de 1 a 5 e imprima-a na tela.

numeros = [1, 2, 3, 4, 5]
# print(numeros)

# Exercício 2: Acesse e imprima o terceiro elemento da lista numeros.

# print(numeros[3])

# Exercício 3: Adicione o número 6 à lista numeros e imprima a lista atualizada

# numeros.append(6)
# print(numeros)

# **Exercício 4:** Remova o número 3 da lista `numeros` e imprima a lista resultante.

# numeros.remove(3)
# print(numeros)

# Exercício 5: Crie uma lista chamada frutas contendo três nomes de frutas diferentes. Em seguida, concatene essa lista com a lista numeros e imprima o resultado.

# frutas = ["Abacaxi", "pessego", "uva"]
# print(numeros, frutas)

# **Exercício 6:** Use um loop `for` para percorrer e imprimir todos os elementos da lista `frutas`.
# for i in frutas:
#     print(i)

# Exercício 7: Verifique se o número 5 está presente na lista numeros e imprima uma mensagem informando se ele está na lista ou não.